### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@1.x

### ISSUE THREAD

**Issue by mturnwall** [webpack/grunt-webpack#68]
I installed grunt-webpack and I get the error

```
├── UNMET PEER DEPENDENCY webpack@1.x
└── UNMET PEER DEPENDENCY webpack-dev-server@1.x
```
I have webpack 1.12.14 installed globally. Do I still need to install locally into my project?

**Comment by sudanvellakovilkanakavel** [comment]
UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

experiencing similar error in the process of setting up React Node.js  environment.Me to searching for the solution.Kindly someone help.I am new to Node.

**Comment by haifengkao** [comment]
`npm install --save-dev webpack`
`npm install --save-dev webpack -dev-server`

**Comment by sudanvellakovilkanakavel** [comment]
Thank you

**Comment by johnyb** [comment]
FYI: if you want to use globally installed peer dependencies, you need to add the global node_modules directory to NODE_PATH. Something like `export NODE_PATH="$(npm prefix -g)/lib/node_modules:$NODE_PATH"` on Linux/Mac/Unix should do the trick.

Peer dependencies are not installed automatically any longer since npm@3.

**Comment by danez** [comment]
global installation of webpack is not supported. And @johnyb workaround should work.
